"""Filter option lists derived from the Defect inventory sheet."""

from __future__ import annotations

FILTER_OPTIONS: dict[str, object] = {
    "regions": [
        "Nose",
        "Scalp",
        "Forehead",
        "Temple",
        "Periorbital",
        "Ear",
        "Cheek",
        "Chin",
        "Lip",
        "Neck",
    ],
    "sub_locations": {
        "Nose": [
            "Dorsum",
            "Sidewall",
            "Tip",
            "Ala",
            "Columella",
            "Other",
        ],
        "Scalp": ["Frontal", "Vertex", "Occipital", "Parietal"],
        "Forehead": ["Central", "Lateral"],
        "Temple": [],
        "Periorbital": [
            "Brow",
            "Upper Lid",
            "Lower Lid",
            "Medial Canthus",
            "Lateral Canthus",
            "Glabella",
        ],
        "Ear": ["Helix", "Central Ear"],
        "Cheek": ["Medial", "Lateral", "Middle"],
        "Chin": [],
        "Lip": ["Upper", "Lower", "Vermillion", "Philtrum", "Commissure"],
        "Neck": [],
    },
    "full_thicknesses": ["Yes", "No", "N/A"],
    "methods_of_repair": [
        "Local flap",
        "Graft",
        "Regional flap",
        "Second intention",
        "Free flap",
    ],
    "general_flaps": [
        "advancement flap",
        "rotation flap",
        "interpolated flap",
        "transposition",
        "island flap",
        "pedicled",
        "n/a",
    ],
    "specific_flap_descriptions": [
        "forehead",
        "melolabial",
        "bilateral advancement",
        "A-T",
        "O-T",
        "V-Y",
        "W-plasty",
        "Z-plasty",
        "cervicofacial",
        "cheek flap",
        "bilobe",
        "rhombic",
        "Helical advancement",
        "Karapandzic",
        "East-West",
        "wedge",
        "scalp flap",
        "other",
        "n/a",
    ],
    "grafts": [
        "n/a",
        "FTSG",
        "cartilage",
        "skin and cartilage",
        "skin and perichondrium",
        "dermal substitute",
        "STSG",
        "other",
    ],
    "graft_donor_sites": [
        "n/a",
        "skin",
        "Ear",
        "septum",
        "rib",
        "standing cutaneous deformity",
        "other",
    ],
}

PATIENT_COLUMNS = [
    "folder_name",
    "patient_id",
    "location_raw",
    "defect_size",
    "full_thickness",
    "method_of_repair",
    "general_flap",
    "specific_flap_description",
    "graft",
    "graft_donor_site",
    "notes",
]
